<?php 
	$_SESSION['randSalt'] = Rand();			
	$salt_server = $_SESSION['randSalt'];			
	echo $this->element('get_captcha_random_code');
	$captchacode = $_SESSION["code"];	
?>

<div class='login-page'>
<div class="col-md-6  col-md-offset-3 login-page-window1">
	<div class="col-md-12 col-sm-12 col-sm-offset-0 col-lg-8 col-md-offset-2 login-page-window2">	
	
		<?php echo $this->Form->create(null, array('type'=>'file', 'enctype'=>'multipart/form-data', 'id'=>'login')); ?>		
		
		  <div class="container1 login-page-background">
		  
			<div class="login-heading-title"><h1 class='hr'><?php echo $logititle; ?></h1></div>
			<div class="form-group ">
				<label class="control-label " for="uname"><b>Username</b></label>
				<div class="input-group">
					<div class="input-group-addon">
						<span class="glyphicon glyphicon-user"></span> 
					</div>
					<input class="form-control login-input-fields" type="text" name="username" autocomplete="off" placeholder="Enter User Name Like 000/00XYZ0000" id="username" >									
				</div>
				<div id="error_username"></div>
			</div>
			<div class="form-group ">
				<label class="control-label " for="psw"><b>Password</b></label>
				<div class="input-group">
					<div class="input-group-addon">
						<span class="glyphicon glyphicon-lock"></span> 
					</div>
					<input class="form-control login-input-fields" type="password" name="password" autocomplete="off" placeholder="**************" id="password" >
				</div>
				<div id="error_password"></div>		
			</div>
			<div class="cpt">
				<div class="col-6 col-md-4 col-sm-4 col-lg-4 col-xl-4 cpt-img d-inline-block">
					<span id="captcha_img"><?php echo $this->Html->image(array('controller'=>'users','action'=>'create_captcha'),array('class'=>'captcha','alt'=>'captcha')); ?></span>					
				</div>
				<div class="col-4 col-md-2 col-sm-2 col-lg-2 col-xl-2 cpt-img rfs-img d-inline-block">
					<a class="" href="javascript:void(0);" onclick="get_new_captcha()" id="new_captcha" title="Get new Image">
						<img src="<?php echo $this->request->getAttribute('webroot');?>img/home/refresh_button.jpg">
					</a>
				</div>
				<div class="col-md-6 col-sm-6 col-lg-6 col-xl-6 cpt-img">
					<input type="text" name="captcha" autocomplete="off" id="captcha" class="form-control" placeholder="Please enter captcha" >										
				</div>
				<div id="error_captchacode" class="errormsg"><?php if(isset($captcha_error_msg)){ echo $captcha_error_msg; } ?></div>
			</div>
			
		    <?php echo $this->Form->control('salt_value', array('label'=>'', 'id'=>'salt_value', 'type'=>'hidden', 'value'=>$salt_server)); ?>
			
			<button type="submit" name='submit' id='Login' value='Login' class='login-button' onclick='myFunction();return false'>Login</button>
			<span class="psw"><?php //echo link_to('Forgot password ?', 'auth/forgotPassword', array('class' => 'login_watag')); ?></span>
			<div class='clearfix'></div>
			<div class="container1" style="font-size: 14px;color: red;">
				Mine Owner should use the credentials generated by form M for the first time login and other user should use the credential generated by the system.
			</div>
			
		  </div>
		<?php  echo $this->Form->end(); ?>
	</div>
</div>
<div class='clearfix'></div>
</div>
